name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/AryanSingh833-Multiplayer-Snake-Game-Platform-AWS-Docker-CI-CD

            git pull origin main

            docker stop snake || true
            docker rm snake || true

            docker build -t snake .
            docker run -d -p 80:80 --name snake snake